### ISSUE TITLE
BUG: Fix failure to download openshift-install binary along with openshift client 'oc' binary

### ISSUE THREAD

**Issue by usrbinkat** [CodeSparta/collector-infra#9]
BUG: no openshift-install binary in bundle https://github.com/CodeSparta/collector-ocp/blob/master/collector/dependencies.yml

```
propose pseudo code:

    - name: "{{ ansible_name_module }} | unarchive:openshift-client-linux.tar.gz | Downloading OC Client {{ openshift_version }}"
      unarchive:
        remote_src: yes
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-install-linux.tar.gz"
        dest: '{{ dir_bin }}'
        mode: 0775

    - name: '{{ ansible_name_module }} | command:cmd | Test Binaries'
      command:
        cmd: '{{ item.bin }} {{ item.exec }}'
      with_items:
        - { bin: '{{ dir_bin }}/oc',  exec: 'version --client' }
        - { bin: '{{ dir_bin }}/openshift-install',  exec: 'version' }
```
